### ISSUE TITLE
Invalid tar header

### ISSUE THREAD

**Issue by deybhayden** [edib-tool/mix-edib#1] opened 2016-02-29 23:05 UTC
Hi, I'm very new to the Elixir world and am trying to build a Docker image based on a sample project to deploy to Amazon Elastic Beanstalk. I saw this tool, and it looked to be a really good fit. However, I'm getting the below error:

```
$> mix edib -n phrontend_api -t latest
.
.
.
==> Artifact successfully created.
==> Creating docker image ...
| $> cat /Users/me/Repos/phrontend_api/tarballs/20160229_225814/phrontend_api-0.0.1.tar.gz | docker import --change 'CMD trap exit TERM; /app/bin/phrontend_api foreground & wait' - phrontend_api:latest
| Error response from daemon: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
| cat: write error: Broken pipe
==> An error happened!
==> Reason: Image command 'cat /Users/me/Repos/phrontend_api/tarballs/20160229_225814/phrontend_api-0.0.1.tar.gz | docker import --change 'CMD trap exit TERM; /app/bin/phrontend_api foreground & wait' - phrontend_api:latest' failed
```

I'm running docker & docker-machine through Virtualbox on my Mac. My current docker version is 1.9.1. Any good troubleshooting tips? Thanks!

**Comment by asaaki** [comment] 2016-03-01 01:06
Thanks for reporting the issue.
I haven't got any real tips, as I have to try to reproduce it.
Could you maybe update docker (current version should be 1.10.2), try to use https://www.docker.com/products/docker-toolbox for OSX.

I had 1.9.0 previously and no issues yet.
Tested it now with the latest docker version (provided via above mentioned docker toolbox) and also could create a test app image.

The tools I use:

```
$ docker-machine -v
docker-machine version 0.6.0, build e27fb87
$ docker -v
Docker version 1.10.2, build c3959b1
$ tar --version
bsdtar 2.8.3 - libarchive 2.8.3
```

Also tried with `gnu-tar` via homebrew:

```
$ tar --version
tar (GNU tar) 1.28
```

… which seems to work as well.

So, I'm not sure why it fails and what is the cause. (I have no docker 1.9.1 for testing.)

**Comment by deybhayden** [comment] 2016-03-01 15:42
Thanks for the heads up, I'm updating Docker Toolbox now. I have gnu-tar at the same version, so hoping it's just a Docker version issue.

**Comment by deybhayden** [comment] 2016-03-01 16:04
So, no luck with the newer versions of the docker tools. Looks like our tool versions are the same, but I'm still running into issues. I'm attaching my build log here - to see if anything looks suspect to you. Thanks!

[build.txt](https://github.com/edib-tool/mix-edib/files/153073/build.txt)

**Comment by asaaki** [comment] 2016-03-01 16:33
Haven't checked the log yet, but could you try some more things?

```
# alternative docker import using no pipe

docker import \
  --change 'CMD trap exit TERM; /app/bin/phrontend_api foreground & wait' \
  /Users/me/Repos/phrontend_api/tarballs/20160229_225814/phrontend_api-0.0.1.tar.gz \
  phrontend_api:latest
```

Also try to open the gzipped tarball with other tools (as well as the `tar` command shipped with OSX).
I would just try to make sure the tarball archive itself is not corrupted.

Another thing you could try would be to remove the current edib-tool docker image and let edib refetch it from the Docker Hub.
With that we could eliminate a broken tool within the build image.

To verify the image state:

```
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
edib/edib-tool        1.1                 3ffd9137a559        5 days ago          440.3 MB
```

(`3ffd9137a559` is the latest build hash of the image.)

**Comment by deybhayden** [comment] 2016-03-01 16:55
Docker import still fails for me with the invalid tar header message:

```
Error response from daemon: Untar re-exec error: exit status 1: output: archive/tar: invalid tar header
```

I'm able to expand the tarball with `gnu-tar` and list the contents successfully with `tar --list -f tarballs/20160301_155228/phrontend_api-0.0.1.tar.gz`. I also had the same success with the shipped osx bsdtar.

I'll report back after blowing away the edib-tool, but I my tag and image id did match before removing it.

**Comment by deybhayden** [comment] 2016-03-01 17:00
No luck with redownloading the edib-tool image. :frowning:

**Comment by asaaki** [comment] 2016-03-01 17:05
Hm, okay. Maybe it's time for me to push the next release for the mix task (and tool), though I wanted to raise the test coverage much higher before doing so. :sweat_smile:

**Comment by esselius** [comment] 2016-03-15 20:43
I hit the same issue.

Docker expects a tarball, but a `tar.gz`-file is piped to `docker import`.

Could be fixed by adding `gunzip` in between `cat` and `docker import`

**Comment by asaaki** [comment] 2016-03-15 23:08
Ah, that makes sense then. (Didn't notice that they changed this behaviour.)

**Comment by asaaki** [comment] 2016-03-15 23:49
I'm still confused.
According to documentation it should be still possible to use a gzipped tarball: https://docs.docker.com/engine/reference/commandline/import/

**Comment by esselius** [comment] 2016-03-15 23:55
> I'm still confused.
> According to documentation it should be still possible to use a gzipped tarball: >https://docs.docker.com/engine/reference/commandline/import/

That's so weird, might be broken maybe?

**Comment by asaaki** [comment] 2016-03-16 00:00
Well, I just realized we could use `gunzip -c` instead of `cat` (it will unzip and stream the uncompressed data); a quick test worked.
Would like to know from @beardedprojamz if that could fix the issue for him, since I can't really reproduce it on my own.
But I guess this could be actually a safer solution than just `cat`ing the gzipped file and we wouldn't need to rely on docker that it may or may not decompress the file.

**Closed as completed** 2016-05-02 13:05 UTC
